#pragma once
#include "Pawn.h"
#include "Board.h"
#include "Rook.h"
#include "Bishop.h"
#include "Queen.h"
#include "Knight.h"
#include "King.h"
Rook RookW;
Rook RookB;
Knight KnightW;
Knight KnightB;
Bishop BishopW;
Bishop BishopB;
Queen QueenW;
Queen QueenB;
King KingW;
King KingB;
Pawn PawnB;
Pawn PawnW;
